FROM ubuntu
MAINTAINER Sohone <guoxh@docomolabs-beijing.com.cn>

RUN apt-get update
RUN apt-get install -y wget

# install Anaconda3
RUN wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-5.2.0-Linux-x86_64.sh -O ~/anaconda3.sh
RUN bash ~/anaconda3.sh -b -p /home/anaconda3 \
	&& rm ~/anaconda3.sh 
ENV PATH /home/anaconda3/bin:$PATH

# install tensorflow
RUN conda install tensorflow -y

# install jieba; rouge; pycorenlp; breadability; gensim
RUN pip install jieba
RUN pip install rouge
RUN pip install pycorenlp
RUN pip install breadability
RUN conda install gensim -y