# cuda:9.0
FROM cuda:9.0
MAINTAINER Sohone <guoxh@docomolabs-beijing.com.cn>

RUN apt-get update
RUN apt-get install -y wget

# install Anaconda3
RUN wget https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh -O ~/anaconda3.sh
RUN bash ~/anaconda3.sh -b -p /home/anaconda3 \
	&& rm ~/anaconda3.sh 
ENV PATH /home/anaconda3/bin:$PATH

# install pytorch
RUN conda install pytorch torchvision cudatoolkit=9.0 -c pytorch
RUN pip install tb-nightly

RUN conda install -c conda-forge opencv
RUN conda install -c defaults libprotobuf protobuf

# install jieba; rouge; pycorenlp; breadability; gensim
RUN pip install util_ds
RUN pip install rouge
# RUN pip install pycorenlp
# RUN pip install breadability
# RUN conda install gensim -y